version: "3"
services:
    app:
        build:
            context: .
            dockerfile: ./Dockerfile
        env_file:
            - ./.env
        ports: 
            - "80:80"
        volumes:
            - ./app/:/var/www/html/
        networks:
            - default