version: "3"
services:
    app:
        build:
            context: .
            dockerfile: ./Dockerfile
        env_file:
            - ./.env
        ports: 
            - "80:80"
        volumes:
            - ./app/:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mariadb
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: wordpress_local
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
            MYSQL_HOST: localhost
            MYSQL_PORT: 3306
        networks:
            - default
#     phpmyadmin:
#         image: phpmyadmin/phpmyadmin
#         links: 
#             - db:db
#         ports:
#             - 8000:80
#         environment:
#             MYSQL_USER: user
#             MYSQL_PASSWORD: test
#             MYSQL_ROOT_PASSWORD: test
# volumes:
#     persistent:
